examples/co/ajax_upload/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('ajax_upload.views',
    url(r'^$', 'upload', name='ajax-upload'),
)

examples/co/co/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
admin.autodiscover()

urlpatterns = patterns('',
     url(r'^$', 'main.views.home', name='home'),
     url(r'^rosetta/', include('rosetta.urls')),
     url(r'^course/', include('course.ajax_urls')),
     url(r'', include('social_auth.urls')),
     url(r'^admin/', include(admin.site.urls)),
     url(r'^ckeditor/', include('ckeditor.urls')),
     url(r'^videolearn/', include('videolearn.urls')),
     url(r'^liqpay/', include('liqpay.urls')),
     url(r'^redactor/', include('redactor.urls')),
)

urlpatterns += i18n_patterns('',
     url(r'^logout/$', 'django.contrib.auth.views.logout',{'next_page': '/'}, name='logout'),
     url(r'^course/', include('course.urls')),
     url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
     url(r'^accounts/profile/$', 'main.views.cabinet', name='my_profile'),
     url(r'^cabinet/$', 'main.views.cabinet', name='cabinet'),
     url(r'^edit/profile/$', 'main.views.profile', name='edit_profile'),
     url(r'^accounts/', include('registration.backends.default.urls')),
     
     url(r'^grappelli/', include('grappelli.urls')), 
     url(r'^$', include('django.contrib.flatpages.urls')),
     url(r'^ajax-upload/', include('ajax_upload.urls')),
     
     
     url(r'^change_language/', 'main.views.change_language', name='change_language'),
     url(r'^lesson/edit/(?P<id>[^\.]+).html', 'course.views.lesson_edit', name="lesson-edit"),


     
)


from django.conf import settings
from django.conf.urls.static import static
urlpatterns += [
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

examples/co/videolearn/urls.py
from django.conf.urls import patterns, url
from videolearn.views import *
from videolearn.ajax import *

urlpatterns = patterns('',
    url(r'^test$', test ),
    url(r'^course/new$', edit_course, {}, name='create-vcourse'),
    url(r'^course/edit/(?P<id>\d+)/$', edit_course, {}, 'edit-vcourse'),
    url(r'^course/delete/(?P<id>\d+)/$', delete_course, {}, 'delete-vcourse'),
    url(r'^course/list$', list_courses, name='list-vcourse'),
    url(r'^lecture/new/(?P<course_id>\d+)$', edit_lecture, {}, name='add-lecture'),
    url(r'^lecture/edit/(?P<id>\d+)/(?P<course_id>\d+)$', edit_lecture, {}, 'edit-lecture'),
    url(r'^lecture/delete/(?P<lecture_id>\d+)$', delete_lecture, {}, 'delete-lecture'),
    url(r'^lecture/start/(?P<id>\d+)$', start_lecture, {}, name='start-lecture'),
    url(r'^detail/(?P<slug>[^\.]+).html$', detail, name='vcourse-detail'),
    url(r'^lecture/preview/(?P<id>\d+)$', preview, name='vcourse-preview'),
    url(r'^lecture/show/(?P<id>\d+)$', show, name='vcourse-show'),
    url(r'^lecture/buy/(?P<id>\d+)$', buy, name='vcourse-buy'),
    url(r'^lecture/testbuy/(?P<id>\d+)$', testbuy, name='test-buy'),
    url(r'^library/$', library, name='library-vcourse'),

    url(r'^article/new/(?P<lesson_id>\d+)$', edit_article, {}, name='add-article'),
    url(r'^article/edit/(?P<id>\d+)/(?P<lesson_id>\d+)$', edit_article, {}, name='edit-article'),
    url(r'^article/show/(?P<id>\d+)$', show_article, {}, name='article-detail'),

    ## AJAX
    url(r'^ajax/test_show$', test_show ),
    url(r'^ajax/course-list$', course_list, name='course-list'),
    url(r'^ajax/material-list$', material_list, name='material-list'),

)

examples/co/videolearn/models.py
from django.db import models
from django.utils.translation import ugettext as _
from ckeditor.fields import RichTextField
import pytils
from django.contrib.auth.models import User
from image_cropping import ImageCropField, ImageRatioField
from easy_thumbnails.files import get_thumbnailer
from django.utils.safestring import mark_safe
import os
from uuid import uuid4
from django.core.urlresolvers import reverse
from redactor.fields import RedactorField


class Vcourse(models.Model):
    TYPES = ( ('v', _('Video')), ('a', _('Audio')) )
    type = models.CharField(max_length = 2, choices = TYPES, default = 'v', verbose_name = _('Type'))
    name = models.CharField(max_length=250, blank=True, verbose_name=_(u'Name'))
    desc = models.TextField(blank=True, verbose_name=_(u'Description'))
    requirements = models.TextField(blank=True, verbose_name=_(u'Requirements'))
    owner = models.ForeignKey(User, verbose_name=_(u'Owner'))
    image = models.ImageField(blank=True, verbose_name=_(u'Image'), upload_to='vcourse_images', null = True)
    cropping = ImageRatioField('image', '200x200', size_warning=True)
    is_active = models.BooleanField(verbose_name=_('Is published?'), default=False)
    on_delete = models.BooleanField(verbose_name=_('Deleted?'), default=False)
    name_slug = models.CharField(verbose_name='Name slug',max_length=250, blank=True)
    price = models.DecimalField(default=0, max_digits=5, decimal_places=2)
    def __unicode__(self):
        return self.name
    def get_absolute_url(self):
       return reverse("vcourse-detail", kwargs={"slug": self.name_slug})
    @property
    def thumb(self):
        try:
            thumbnail_url = get_thumbnailer(self.image).get_thumbnail({
                'size': (100, 100),
                'box': self.cropping,
                'crop': True,
                'detail': True,
            }).url
            return mark_safe(u'<img src="%s" />' % thumbnail_url)
        except:
            return 'no image'
    def save(self, **kwargs):
        if not self.id:
            self.name_slug = pytils.translit.slugify(self.name)
        return super(Vcourse, self).save(**kwargs)

def path_and_rename(path):
    def wrapper(instance, filename):
        ext = filename.split('.')[-1]
        # get filename
        if instance.pk:
            filename = '{}.{}'.format(instance.pk, ext)
        else:
            # set filename as random string
            filename = '{}.{}'.format(uuid4().hex, ext)
        # return the whole path to the file
        return os.path.join(path, filename)
    return wrapper

class Vlesson(models.Model):
    name = models.CharField(max_length=250, blank=True, verbose_name=_(u'Name'))
    desc = models.TextField(blank=True, verbose_name=_(u'Description'))
    is_active = models.BooleanField(verbose_name=_('Is main?'), default=False)
    owner = models.ForeignKey(User, verbose_name=_(u'Owner'))
    course = models.ForeignKey(Vcourse, verbose_name=_(u'Course'), blank=True, null = True)
    video = models.FileField(blank=True, verbose_name=_(u'Video'), upload_to=path_and_rename('vcourse_video'), null = True)
    is_converted = models.BooleanField(verbose_name=_('Is converted?'), default=False)
    is_error = models.BooleanField(verbose_name=_('Is converted?'), default=False)
    error_desc = models.TextField(blank=True, verbose_name=_(u'Error description'))
    is_free = models.BooleanField(verbose_name=_('Is free?'), default=False)
    name_slug = models.CharField(verbose_name='Name slug',max_length=250, blank=True)
    duration = models.CharField(verbose_name='Duration',max_length=250, blank=True)
    price = models.DecimalField(default=0, max_digits=5, decimal_places=2)
    is_public = models.BooleanField(verbose_name=_('Is public?'), default=True)
    image = models.ImageField(blank=True, verbose_name=_(u'Image'), upload_to='vcourse_images', null = True)
    cropping = ImageRatioField('image', '200x155', size_warning=True)
    number = models.PositiveIntegerField(
        verbose_name=_(u'Number'),
        default=0)
    def get_absolute_url(self):
       return reverse("start-lecture", kwargs={"id": self.id})
    @property
    def file_name(self):
        return str(self.video).split('/')[1]     
    @property
    def screenshot(self):
        try:
            thumbnail_url = get_thumbnailer(self.image).get_thumbnail({
                'size': (200, 155),
                'box': self.cropping,
                'crop': True,
                'detail': True,
            }).url
            return mark_safe(u'<img src="%s" />' % thumbnail_url)
        except:
            return 'no image'
        return 'no'

        
 
    @property
    def price_str(self):
        if self.is_free or self.price == 0:
            return u'free'
        else:
            return self.price    

    def __unicode__(self):
        return self.name
    def save(self, **kwargs):
        if not self.id:
            self.name_slug = pytils.translit.slugify(self.name)
            if self.video.path.split('.')[-1] == 'flv':
                self.is_converted = True
        return super(Vlesson, self).save(**kwargs)


def gidrate_lessons(lessons,user):
    from liqpay.models import Liqpay
    #import pdb; pdb.set_trace()
    for l in lessons:
        if l.price==0:
            l.is_byed = True
        else:
            try:
                b = Liqpay.objects.get(user=user,lesson=l,is_success=True)
                l.is_byed = True
            except:
                l.is_byed = False   
    return lessons


class Varticles(models.Model):
    name = models.CharField(max_length=250, blank=True, verbose_name=_(u'Name'))
    desc = RedactorField(blank=True, verbose_name=_(u'Description'))
    adesc = RedactorField(blank=True, verbose_name=_(u'Description additional'))
    lesson = models.ForeignKey(Vlesson, verbose_name=_(u'Course'), blank=True, null = True)
    name_slug = models.CharField(verbose_name='Name slug',max_length=250, blank=True)
    pub = models.BooleanField(verbose_name=_('Is published?'), default=True)
    sound = models.FileField(blank=True, verbose_name=_(u'Sound'), upload_to=path_and_rename('vcourse_sound'), null = True)
    owner = models.ForeignKey(User, verbose_name=_(u'Owner'))
    is_free = models.BooleanField(verbose_name=_('Is free?'), default=False)
    def get_absolute_url(self):
       return reverse("article-detail", kwargs={"id": self.id})
    def __unicode__(self):
        return self.name
    def save(self, **kwargs):
        if not self.id:
            self.name_slug = pytils.translit.slugify(self.name)
        return super(Varticles, self).save(**kwargs)

class Vsounds(models.Model):
    sound = models.FileField(blank=True, verbose_name=_(u'Sound'), upload_to=path_and_rename('vcourse_sound'), null = True)
    article = models.ForeignKey(Varticles)
    pub = models.BooleanField(verbose_name=_('Is published?'), default=True)

class Vimages(models.Model):
    image = models.ImageField(blank=True, verbose_name=_(u'Image'), upload_to='course_images')
    cropping = ImageRatioField('image', '100x100', size_warning=True)
    article = models.ForeignKey(Varticles)
    def __unicode__(self):
        thumbnail_url = get_thumbnailer(self.image).get_thumbnail({
            'size': (100, 100),
            'box': self.cropping,
            'crop': True,
            'detail': True,
        }).url
        return mark_safe(u'<img src="%s" />' % thumbnail_url)
    @property
    def thumb(self):
        thumbnail_url = get_thumbnailer(self.image).get_thumbnail({
            'size': (250, 250),
            'box': self.cropping,
            'crop': True,
            'detail': True,
        }).url
        return mark_safe(u'<img src="%s" />' % thumbnail_url)



class Access(models.Model):
    created = models.DateTimeField(auto_now_add=True, auto_now=True, blank=True, null=True)
    user = models.ForeignKey(User)
    lesson = models.ForeignKey(Vlesson, verbose_name=_(u'Lesson'), blank=True, null = True)
    alias = models.CharField(verbose_name='Alias',max_length=250, blank=True)
    def save(self, **kwargs):
        from co.settings import BASE_DIR
        from subprocess import call
        if not self.id:
            fname = uuid4().hex
            self.alias = fname
            lnk = 'ln -P %s %s' % (self.lesson.video.path,BASE_DIR+'/media/access/'+fname+'.flv')
            print lnk
            call(lnk,shell=True)
        return super(Access, self).save(**kwargs)

examples/co/videolearn/forms.py
from ajax_upload.widgets import AjaxClearableFileInput
from django import forms
from videolearn.models import *
from ajax_upload.widgets import AjaxClearableFileInput
from ckeditor.widgets import CKEditorWidget
from image_cropping import ImageCropWidget




        


class VcourseForm(forms.ModelForm):
    class Meta:
        model = Vcourse
        fields = ( 'name', 'desc', 'requirements' ,'image', 'cropping', 'owner', 'price', 'type' )
        widgets = {
            'desc': CKEditorWidget(config_name='small'),
            'requirements': CKEditorWidget(config_name='small'),
            'image': ImageCropWidget,
            'owner': forms.HiddenInput(),
        }



class VlessonForm(forms.ModelForm):
    class Meta:
        model = Vlesson
        fields = ( 'number', 'name' , 'desc', 'owner', 'course', 'video', 'price' )
        widgets = {
            'owner': forms.HiddenInput(),
            'course': forms.HiddenInput(),
            'desc': CKEditorWidget(config_name='small'),
        }



class VarticleForm(forms.ModelForm):
    class Meta:
        model = Varticles
        fields = ( 'name', 'desc', 'adesc', 'lesson', 'sound', 'owner', 'is_free' )
        widgets = {
            'owner': forms.HiddenInput(),
            'lesson': forms.HiddenInput(),
        }       

examples/co/videolearn/templates/a_course_list.html
{% load i18n %}


<div class="col-md-12">
 <h2>{% trans 'My courses' %}</h2>



  <table class="table table-striped">
                <thead>
                    <tr>
                        <th width="10%">{% trans 'Course' %}</th>
                        <th>{% trans 'Lessons' %}</th>
              
                    </tr>
                </thead>
                <tbody>
                    {% for c in courses %}
                    <tr>
                        <td>

                            {{ c.thumb }}
                            <p>{{ c.name }}</p>
                            <p>{% trans 'Published' %}: {{ c.is_active }}</p>
                            <a class="btn btn-warning" onclick="return confirm('{% trans 'Are u sure?' %}') ? true : false;" href="{% url 'delete-vcourse' id=c.id %}"><span class="glyphicon glyphicon-remove"></span></a>
                            <a class="btn btn-warning" href="{% url 'edit-vcourse' id=c.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
                        </td>

                        <td>

                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>{% trans 'Screenshot' %}</th>
                                            <th>{% trans 'Info' %}</th>
                                            <th>{% trans 'Show' %}</th>
                                        </tr>                                        
                                    </thead>
                                    {% for l in c.vlesson_set.all %}
                                        <tr>
                                            <td> <a href="{% url 'vcourse-preview' id=l.id %}" target=_blank>{{ l.screenshot }} </a></td>
                                            <td> 
                                             <p> {{ l.name }}  </p>
                                             <p> <strong>{% trans 'Duration' %}:</strong> {{ l.duration }} </p>
                                             <p> <strong>{% trans 'Price' %}:</strong>{{ l.price_str }} </p>
                                             <p> <strong>{% trans 'Articles' %}:</strong>
                                                
                                                <table class="table table-striped">
                                                    {% for a in l.varticles_set.all %}    
                                                        <tr> 
                                                            <td>{{ a.name }}</td>
                                                            <td><a href="{{ a.get_absolute_url }}">{{ a.name }}</a></td>
                                                            <td><a href="{% url 'edit-article' id=a.id lesson_id=l.id %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
                                                        </tr>
                                                    {% endfor %}
                                                </table>
                                                        <a class="btn btn-primary pull-left" href="{% url 'add-article' lesson_id=l.id %}">
                                                         {% trans 'Add article' %}
                                                         </a>                                                
                                             </p>
                                            </td>
                                            <td>
                                                <div class="btn-toolbar" role="toolbar">
                                                    <div class="btn-group" role="group">
                                                        <a class="btn btn-primary pull-left" href="{% url 'edit-lecture' id=l.id course_id=c.id %}">
                                                         <span class="glyphicon glyphicon-pencil"></span>
                                                          </a> 
                                                    </div>
                                                    <!--<a href="#" class="test_show" data-id="{{ c.id }}"> {% trans 'Show' %} </a>-->
                                                    {% if l.is_converted %}
                                                    <div class="btn-group" role="group">
                                                        <a class="btn btn-primary pull-right" href="{% url 'vcourse-preview' id=l.id %}" target=_blank>



                                                        <span class="glyphicon glyphicon-eye-open"></span></a>

                                                        <a class="btn btn-warning" onclick="return confirm('{% trans 'Are u sure?' %}') ? true : false;" href="{% url 'delete-lecture' lecture_id=l.id %}"><span class="glyphicon glyphicon-remove"></span></a>

                                                        
                                                    </div>
                                                    {% endif %}
                                                </div>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </table>
                            
 

<a class="btn btn-primary" href="{% url 'add-lecture' course_id=c.id %}">{% trans 'Add lecture' %}</a> 

                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
        </table>




</div>

examples/co/videolearn/templates/buy.html
{% extends 'base.html' %}


{% block content %}

    <div class="well">

        <h1 align="center">Подтвердите покупку "{{ lesson.name }}"</h1>
            <h2 align="center"> {{ lesson.price }} грн. </h2>

        <br />

        <div style="text-align: center">{{ button | safe }}

    </div>

{% endblock %}

examples/co/videolearn/templates/buy_link.html
{% load i18n %}
{% if not l.is_byed %}
  <a class="btn btn-primary pull-right" href="{% url 'vcourse-buy' id=l.id %}"> <span class="glyphicon glyphicon-shopping-cart"> </span> {% trans 'Buy' %} </a>

<a  class="btn btn-success pull-right" href="{% url 'test-buy' id=l.id %}"> <span class="glyphicon glyphicon-eye-open"></span> {% trans 'Test buy' %} </a>

{% else %}
  <a target="_blank"  class="btn btn-success pull-right" href="{% url 'vcourse-show' id=l.id %}"> <span class="glyphicon glyphicon-eye-open"></span> {% trans 'View' %} </a>  

{% endif %}

examples/co/videolearn/templates/edit_varticle.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load i18n %}
{% load thumbnail %}
{% load staticfiles %}
       
{% block js %}
    {{ block.super }}
    {{ form.media }}
        <script type="text/javascript" src="{% static 'django_ajax/js/jquery.ajax.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'django_ajax/js/jquery.ajax-plugin.min.js' %}"></script>
    <script src="{% static 'js/profile.js' %}"></script>
{% endblock %}

{% block bredcrumbs %} {% endblock %}

{% block content %}


<div class="col-md-12">



    <div class="well">
      
         
       
 <form method="post" action="" enctype="multipart/form-data">
                <h2>{% trans 'New/edit article' %}</h2>
                
                {% csrf_token %}
                 {{ form.lesson }}
                 {{ form.owner }}

               

                <div class="form-body">
                    <div class="form-group {%if form.email.errors %}alert alert-danger{%endif%}">
                        {{ form.name.label_tag }}
                        <div class="input-group">
                            <span class="input-group-addon">
                                
                            </span>
                           {{ form.name|add_class:"form-control" }}
                        </div>
                        <span class="error-block">{{ form.name.help_text }}</span>
                        <span class="help-block">{{ form.name.errors }}</span>
                    </div>
                </div>


                <div class="form-body">
                    <div class="form-group {%if form.email.errors %}alert alert-danger{%endif%}">
                        {{ form.desc.label_tag }}
                        <div class="input-group">
                           
                           {{ form.desc|add_class:"form-control" }}
                        </div>

                      

                        <span class="error-block">{{ form.desc.help_text }}</span>
                        <span class="help-block">{{ form.desc.errors }}</span>
                    </div>
                </div>



                <div class="form-body">
                    <div class="form-group {%if form.email.errors %}alert alert-danger{%endif%}">
                        {{ form.sound.label_tag }}
                        <div class="input-group">
                           
                           {{ form.sound|add_class:"form-control" }}
                        </div>

                      

                        <span class="error-block">{{ form.sound.help_text }}</span>
                        <span class="help-block">{{ form.sound.errors }}</span>
                    </div>
                </div>                



                <div class="form-body">
                    <div class="form-group">
                        {{ form.is_free.label_tag }}
                        <div class="">
                           
                           {{ form.is_free|add_class:"form-control" }}
                        </div>

                      

                        <span class="error-block">{{ form.is_free.help_text }}</span>
                        <span class="help-block">{{ form.is_free.errors }}</span>
                    </div>
                </div>                  



               

                    <div class="row">
                        <div class="col-md-6">
                            <button type="submit" class="btn theme-btn" id="registration_save">{% trans 'Save' %}</button>
                        </div>
                        

                        <a class="btn btn-success" href="{% url 'list-vcourse' %}">{% trans 'My video courses' %}</a> 
                    </div>

            </form>

            
           


       <div style="clear: both"></div>
    </div>
    

</div>

     


{% endblock %}

examples/co/videolearn/templates/edit_vcourse.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load i18n %}
{% load thumbnail %}
{% load staticfiles %}
       
{% block js %}
    {{ block.super }}
    {{ form.media }}
        <script type="text/javascript" src="{% static 'django_ajax/js/jquery.ajax.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'django_ajax/js/jquery.ajax-plugin.min.js' %}"></script>
    <script src="{% static 'js/profile.js' %}"></script>
{% endblock %}

{% block bredcrumbs %} {% endblock %}

{% block content %}


<div class="col-md-12">



    <div class="well">
      
         
       
 <form method="post" action="" enctype="multipart/form-data">
                <h2>{% trans 'New/edit course' %}</h2>
                
                {% csrf_token %}
                {{ form.owner }}

                <div class="form-body">
                    <div class="form-group {%if form.email.errors %}alert alert-danger{%endif%}">
                        {{ form.type.label_tag }}
                        <div class="input-group">
                            <span class="input-group-addon">
                                
                            </span>
                           {{ form.type|add_class:"form-control" }}
                        </div>
                        <span class="error-block">{{ form.type.help_text }}</span>
                        <span class="help-block">{{ form.type.errors }}</span>
                    </div>
                </div>


                <div class="form-body">
                    <div class="form-group {%if form.email.errors %}alert alert-danger{%endif%}">
                        {{ form.name.label_tag }}
                        <div class="input-group">
                            <span class="input-group-addon">
                                
                            </span>
                           {{ form.name|add_class:"form-control" }}
                        </div>
                        <span class="error-block">{{ form.name.help_text }}</span>
                        <span class="help-block">{{ form.name.errors }}</span>
                    </div>
                </div>


                <div class="form-body">
                    <div class="form-group {%if form.email.errors %}alert alert-danger{%endif%}">
                        {{ form.desc.label_tag }}
                        <div class="input-group">
                           
                           {{ form.desc|add_class:"form-control" }}
                        </div>
                        <span class="error-block">{{ form.desc.help_text }}</span>
                        <span class="help-block">{{ form.desc.errors }}</span>
                    </div>
                </div>

                <div class="form-body">
                    <div class="form-group {%if form.email.errors %}alert alert-danger{%endif%}">
                        {{ form.price.label_tag }}
                        <div class="input-group">
                           
                           {{ form.price|add_class:"form-control" }}
                        </div>
                        <span class="error-block">{{ form.price.help_text }}</span>
                        <span class="help-block">{{ form.price.errors }}</span>
                    </div>
                </div>



                <div class="form-body">
                    <div class="form-group {%if form.email.errors %}alert alert-danger{%endif%}">
                        {{ form.requirements.label_tag }}
                        <div class="input-group">
                           
                           {{ form.requirements|add_class:"form-control" }}
                        </div>
                        <span class="error-block">{{ form.requirements.help_text }}</span>
                        <span class="help-block">{{ form.requirements.errors }}</span>
                    </div>
                </div>

                <div class="form-body">
                    <div class="form-group {%if form.email.errors %}alert alert-danger{%endif%}">
                        {{ form.image.label_tag }}
                        
                            
                           {{ form.image|add_class:"form-control" }}
                           {{ form.cropping }}
                        
                        <span class="error-block">{{ form.image.help_text }}</span>
                        <span class="help-block">{{ form.image.errors }}</span>
                    </div>
                </div>
               
                   

                    <div class="row">
                        <div class="col-md-6">
                            <button type="submit" class="btn theme-btn" id="registration_save">{% trans 'Save' %}</button>
                        </div>
                        

                        <a class="btn btn-success" href="{% url 'list-vcourse' %}">{% trans 'My video courses' %}</a> 
                    </div>

            </form>

            
           


       <div style="clear: both"></div>
    </div>
    

</div>

     


{% endblock %}

examples/co/videolearn/templates/preview.html
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
    <title>{% trans 'Preview' %}</title>
    <script type="text/javascript" src="/static/swfobject.js"></script>
    <script type="text/javascript">

        window.onload = function()

	{
        var flashVars = {
            streamer: 'rtmp://{{ server }}/vod',
            file:'{{ lesson.file_name }}'
        };
        var params = {};
        params.allowfullscreen = "true";
        var attributes = {};
        swfobject.embedSWF("/static/RtmpPlayer.swf", "rtmp-publisher", "800", "600", "9.0.0", null, flashVars, params, attributes);


    }
    </script>
</head>
<body>
    <p><strong>{% trans 'Press play to start watching!' %}</strong></p>
    <div id="rtmp-publisher">
        <p>Flash not installed</p>
    </div>
</body>
</html>

examples/co/videolearn/templates/show_audio.html
{% extends 'base.html' %}
{% load i18n %}

{% block js %}
    {{ block.super }}
    {{ form.media }}
        
 
{% endblock %}

{% block bredcrumbs %} 
            <!-- BEGIN BREADCRUMBS -->
            <div class="row breadcrumbs" >
                <div class="container">
                    <div class="col-md-3 col-sm-3">
                      <h3> <a href="{{ lesson.course.get_absolute_url }}">{{ lesson.course }}</a></h3>
                    </div>
                    <div class="col-md-9 col-sm-9">
                         
                        
                        <div class="div_uploaded_img" id="from_publisher"> </div>
                    </div>
                </div>
            </div>
            <!-- END BREADCRUMBS -->

 {% endblock %}

{% block content %}
    <h2> {{ lesson.name }} </h2>




                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>{% trans 'Name' %}</th>
                                            <th>{% trans 'Show' %}</th>
                                        </tr>                                        
                                    </thead>

                                {% for a in lesson.varticles_set.all %}
                                        <tr>
                                            <td><a href="{{ a.get_absolute_url }}">{{ a.name }}</a></td>
                                            <td> <a href="{{ a.get_absolute_url }}"> <span class="glyphicon glyphicon-eye-open"></span> </a></td>
                                        </td>
                                {% endfor %}
                                </table>

{% endblock %}