examples/co/ajax_upload/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('ajax_upload.views',
    url(r'^$', 'upload', name='ajax-upload'),
)

examples/co/co/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
admin.autodiscover()

urlpatterns = patterns('',
     url(r'^$', 'main.views.home', name='home'),
     url(r'^rosetta/', include('rosetta.urls')),
     url(r'^course/', include('course.ajax_urls')),
     url(r'', include('social_auth.urls')),
     url(r'^admin/', include(admin.site.urls)),
     url(r'^ckeditor/', include('ckeditor.urls')),
     url(r'^videolearn/', include('videolearn.urls')),
     url(r'^liqpay/', include('liqpay.urls')),
     url(r'^redactor/', include('redactor.urls')),
)

urlpatterns += i18n_patterns('',
     url(r'^logout/$', 'django.contrib.auth.views.logout',{'next_page': '/'}, name='logout'),
     url(r'^course/', include('course.urls')),
     url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
     url(r'^accounts/profile/$', 'main.views.cabinet', name='my_profile'),
     url(r'^cabinet/$', 'main.views.cabinet', name='cabinet'),
     url(r'^edit/profile/$', 'main.views.profile', name='edit_profile'),
     url(r'^accounts/', include('registration.backends.default.urls')),
     
     url(r'^grappelli/', include('grappelli.urls')), 
     url(r'^$', include('django.contrib.flatpages.urls')),
     url(r'^ajax-upload/', include('ajax_upload.urls')),
     
     
     url(r'^change_language/', 'main.views.change_language', name='change_language'),
     url(r'^lesson/edit/(?P<id>[^\.]+).html', 'course.views.lesson_edit', name="lesson-edit"),


     
)


from django.conf import settings
from django.conf.urls.static import static
urlpatterns += [
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

examples/co/course/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
     url(r'^index/$', 'course.views.index', name='course'),
     url(r'^lesson/for/student/(?P<id>\d+).html$', 'course.views.lesson_for_student', name='lesson_for_student'),
     url(r'^lesson/for/owner/(?P<id>\d+).html$', 'course.views.lesson_for_owner', name='lesson_for_owner'),
     url(r'^owner/(?P<lesson_id>\d+).js$', 'course.views.js_for_owner', name='course_owner_js'),
     url(r'^student/(?P<lesson_id>\d+).js$', 'course.views.js_for_student', name='course_student_js'),
     url(r'^lesson/edit/(?P<id>\d+).js$', 'course.views.lesson_edit', name='lesson_edit'),
     url(r'^owner/(?P<lesson_id>\d+)_widget.js$', 'course.views.js_upload_image_widget', name='upload_image_widget'),
     url(r'^add/image$', 'course.views.add_image' , name="add-image"),
     url(r'^enter/(?P<email>[^\.]+)/(?P<token>[^\.]+)$', 'course.views.enter' , name="enter"),
     url(r'^subscribe/(?P<email>[^\.]+)/(?P<lesson_id>\d+)/(?P<token>[^\.]+)$', 'course.views.subscribe' , name="subscribe"),
     url(r'^clear/lesson/(?P<lesson_id>\d+)$', 'course.views.clear_lesson' , name="clear-lesson"),
     url(r'^detail/(?P<slug>[^\.]+).html$', 'course.views.detail', name='course_detail'),
     url(r'^add/me/to/course/(?P<course_id>\d+)$', 'course.views.add_me_to_course' , name="add-me-to-course"),
     url(r'^create/course$', 'course.views.create_course' , name="create-course"),
     url(r'^edit/course/(?P<course_id>\d+)$', 'course.views.edit_course' , name="edit-course"),
     url(r'^delete/course/(?P<course_id>\d+)$', 'course.views.delete_course' , name="delete-course"),
     url(r'^list/of/courses$', 'course.views.courses_list' , name="list-courses"),
     url(r'^create/lesson/(?P<course_id>\d+)$', 'course.views.create_lesson' , name="create-lesson"),
     url(r'^delete/lesson/(?P<lesson_id>\d+)$', 'course.views.delete_lesson' , name="delete-lesson"),
     url(r'^for_innerpage.js$', 'course.views.js_for_innerpage', name='js_for_innerpage'),
)

examples/co/course/models.py
from django.db import models
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from easy_thumbnails.files import get_thumbnailer
from image_cropping import ImageCropField, ImageRatioField
from django.utils.safestring import mark_safe
from main.models import UserProfile
from ckeditor.fields import RichTextField
import pytils

class Course(models.Model):
    name = models.CharField(max_length=250, blank=True, verbose_name=_(u'Name'))
    desc = models.TextField(blank=True, verbose_name=_(u'Description'))
    requirements = models.TextField(blank=True, verbose_name=_(u'Requirements'))
    owner = models.ForeignKey(User, verbose_name=_(u'Owner'))
    image = models.ImageField(blank=True, verbose_name=_(u'Image'), upload_to='course_images', null = True)
    cropping = ImageRatioField('image', '200x200', size_warning=True)
    is_active = models.BooleanField(verbose_name=_('Is main?'), default=False)
    name_slug = models.CharField(verbose_name='Name slug',max_length=250, blank=True)
    def __unicode__(self):
        return self.name
    def get_absolute_url(self):
       return reverse("course_detail", kwargs={"slug": self.name_slug})
    @property
    def thumb(self):
        try:
            thumbnail_url = get_thumbnailer(self.image).get_thumbnail({
                'size': (100, 100),
                'box': self.cropping,
                'crop': True,
                'detail': True,
            }).url
            return mark_safe(u'<img src="%s" />' % thumbnail_url)
        except:
            return 'no image'
    def save(self, **kwargs):
        if not self.id:
            self.name_slug = pytils.translit.slugify(self.name)
        return super(Course, self).save(**kwargs)


class Lesson(models.Model):
    name = models.CharField(max_length=250, blank=True, verbose_name=_(u'Name'))
    desc = models.TextField(blank=True, verbose_name=_(u'Description'))
    is_active = models.BooleanField(verbose_name=_('Is main?'), default=False)
    is_camera_on = models.BooleanField(verbose_name=_('Is camera on?'), default=False)
    start_at = models.DateTimeField(blank = True, null = True)
    owner = models.ForeignKey(User, verbose_name=_(u'Owner'))
    image = models.ImageField(blank=True, verbose_name=_(u'Image'), upload_to='lessons_images', null = True)
    cropping = ImageRatioField('image', '100x100', size_warning=True)
    course = models.ForeignKey(Course, verbose_name=_(u'Course'), blank=True, null = True)
    is_runing = models.BooleanField(verbose_name=_('Is runing?'), default=False)
    @property
    def thumb(self):
        try:
            thumbnail_url = get_thumbnailer(self.image).get_thumbnail({
                'size': (50, 50),
                'box': self.cropping,
                'crop': True,
                'detail': True,
            }).url
            return mark_safe(u'<img src="%s" />' % thumbnail_url)
        except:
            return 'no image'
    def __unicode__(self):
        return self.name
    def get_absolute_url_for_student(self):
       return reverse("lesson_for_student", kwargs={"id": self.pk})
    def get_absolute_url_for_owner(self):
       return reverse("lesson_for_owner", kwargs={"id": self.pk})
    def clear(self):
        Images.objects.filter(lesson=self).delete()
        ChatMessages.objects.filter(lesson=self).delete()
        Event.objects.filter(lesson=self).delete()
        Users2Lesson.objects.filter(lesson=self).delete()
            

class Topic(models.Model):
    name = models.CharField(max_length=250, blank=True, verbose_name=_(u'Name'))
    lesson = models.ForeignKey(Lesson, verbose_name=_(u'Lesson'))
    def __unicode__(self):
        return self.name

class Event(models.Model):
    TP = (
                ('text_add', _(u'Text adding')),
                ('text_replace', _(u'Text replacing')),
                ('image_file', _(u'Image file')),
                ('image_url', _(u'Image url')),
                ('clear', _(u'Clear')),
          )
    tp = models.CharField(verbose_name=_(u'Type of event'),
                                 choices=TP,
                                 default='text_add',
                                 max_length=15,
                                 db_index=True)
    image_file = models.ImageField(upload_to='event_image', verbose_name=_('Image file'), blank=True)
    image_url = models.CharField(max_length=250, blank=True, verbose_name=_(u'Image url'))
    text = models.TextField(blank=True, verbose_name=_(u'Text'))
    lesson = models.ForeignKey(Lesson, verbose_name=_(u'Topic'))
    created = models.DateTimeField(auto_now_add = True, auto_now = True, blank = True, null = True)
    sorting = models.IntegerField(blank=True, null = True)
    text_size = models.CharField(max_length=50, blank=True, verbose_name=_(u'Text size'))
    text_color = models.CharField(max_length=50, blank=True, verbose_name=_(u'Text color'))
    text_align = models.CharField(max_length=50, blank=True, verbose_name=_(u'Text align'))
    @property
    def li_item(self):
        ret = '''
                <li id="event_%s"> 
                <a data-id="%s" onclick="return false" href="#" class="delete_event"><span class="glyphicon glyphicon-remove"> </span></a> 
                  %s
                <a data-id="%s" onclick="return false" href="#" class="move_event_to_incubator"><span class="glyphicon glyphicon-arrow-right"> </span></a>
                </li>               
                ''' % (self.id, self.id, self.__unicode__(), self.id)
        return mark_safe(ret)
    @property
    def thumb(self):
            return mark_safe(u'<img width="200" src="%s" />' % self.text)
    def __unicode__(self):
        if (self.tp=='image_file'):
            return self.thumb    
        else:
            return self.text
    def save(self, **kwargs):
        if not self.id:
            try:
                self.sorting = Event.objects.all().order_by('-id')[0:1][0].id+1
            except:
                self.sorting = 1
        return super(Event, self).save(**kwargs)

class Images(models.Model):
    image = models.ImageField(blank=True, verbose_name=_(u'Image'), upload_to='course_images')
    cropping = ImageRatioField('image', '100x100', size_warning=True)
    lesson = models.ForeignKey(Lesson)
    created = models.DateTimeField(auto_now_add = True, auto_now = True, blank = True, null = True)
    publish = models.CharField(max_length=5, blank=True, verbose_name=_(u'Auto publish'))
    def __unicode__(self):
        thumbnail_url = get_thumbnailer(self.image).get_thumbnail({
            'size': (50, 50),
            'box': self.cropping,
            'crop': True,
            'detail': True,
        }).url
        return mark_safe(u'<img src="%s" />' % thumbnail_url)
    @property
    def link(self):
        thumbnail_url = get_thumbnailer(self.image).get_thumbnail({
            'size': (50, 50),
            'box': self.cropping,
            'crop': True,
            'detail': True,
        }).url
        return mark_safe(u'<a id="uploaded_image_%s" class="uploaded_image" data-replace="yes" href="#" data-filename="%s"><img src="%s" /></a>' % (self.id, '/media/'+str(self.image), thumbnail_url))


class Users2Lesson(models.Model):
    lesson = models.ForeignKey(Lesson)
    user = models.ForeignKey(UserProfile)

class Users2Course(models.Model):
    course = models.ForeignKey(Course)
    user = models.ForeignKey(UserProfile)


class Subscriber2Lesson(models.Model):
    lesson = models.ForeignKey(Lesson)
    user = models.ForeignKey(UserProfile)

class ChatMessages(models.Model):
    user = models.ForeignKey(UserProfile)
    text = models.TextField(blank=True, verbose_name=_(u'Text'))
    lesson = models.ForeignKey(Lesson, verbose_name=_(u'Lesson'))
    created = models.DateTimeField(auto_now_add = True, auto_now = True, blank = True, null = True)



class Incubator(models.Model):
    TP = (
                ('text_add', _(u'Text adding')),
                ('text_replace', _(u'Text replacing')),
                ('image_file', _(u'Image file')),
                ('image_url', _(u'Image url')),
                ('clear', _(u'Clear')),
          )
    tp = models.CharField(verbose_name=_(u'Type of event'),
                                 choices=TP,
                                 default='text_add',
                                 max_length=15,
                                 db_index=True)
    image_file = models.ImageField(upload_to='event_image', verbose_name=_('Image file'), blank=True)
    image_url = models.CharField(max_length=250, blank=True, verbose_name=_(u'Image url'))
    text = models.TextField(blank=True, verbose_name=_(u'Text'))
    lesson = models.ForeignKey(Lesson, verbose_name=_(u'Topic'))
    created = models.DateTimeField(auto_now_add = True, auto_now = True, blank = True, null = True)
    sorting = models.IntegerField(blank=True, null = True)
    text_size = models.CharField(max_length=50, blank=True, verbose_name=_(u'Text size'))
    text_color = models.CharField(max_length=50, blank=True, verbose_name=_(u'Text color'))
    text_align = models.CharField(max_length=50, blank=True, verbose_name=_(u'Text align'))
    @property
    def li_item(self):
        ret = '''
                <li id="incubator_%s"> 
                <a data-id="%s" onclick="return false" href="#" class="move_incubator_to_event"><span class="glyphicon glyphicon-arrow-left"> </span></a>
                  %s
                <a data-id="%s" onclick="return false" href="#" class="delete_incubator"><span class="glyphicon glyphicon-remove"> </span></a> 
                </li>               
                ''' % (self.id, self.id, self.__unicode__(), self.id)
        return mark_safe(ret)
    @property
    def thumb(self):
            return mark_safe(u'<img width="200" src="%s" />' % self.text)
    def __unicode__(self):
        if (self.tp=='image_file'):
            return self.thumb    
        else:

examples/co/course/forms.py
from ajax_upload.widgets import AjaxClearableFileInput
from django import forms
from course.models import Images, Course, Lesson
from ajax_upload.widgets import AjaxClearableFileInput
from ckeditor.widgets import CKEditorWidget
from image_cropping import ImageCropWidget

class ImageForm(forms.ModelForm):
    class Meta:
        model = Images
        fields = ( 'image', )
        widgets = {
            'image': AjaxClearableFileInput
        }





class AjaxImageForm(forms.Form):
    my_image_field = forms.ImageField(widget=AjaxClearableFileInput())


class ImportImageForm(forms.ModelForm):
    class Meta:
        model = Images
        fields = ( 'image', 'lesson', 'publish')
        


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ( 'name', 'desc', 'requirements' ,'image', 'cropping', 'owner' )
        widgets = {
            'desc': CKEditorWidget(config_name='small'),
            'requirements': CKEditorWidget(config_name='small'),
            'image': ImageCropWidget,
            'owner': forms.HiddenInput(),
        }



class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ( 'name' ,'image', 'desc', 'cropping', 'owner', 'course' )
        widgets = {
            'image': ImageCropWidget,
            'owner': forms.HiddenInput(),
            'course': forms.HiddenInput(),
            'desc': CKEditorWidget(config_name='small'),
        }

examples/co/course/templates/_lesson_for_student.html
{% extends 'base.html' %}
{% load compress %}
{% load staticfiles %}
{% load i18n %}

{% block js %}

        {{ block.super }}

        <script src="{% static 'sockjs-client/dist/sockjs-0.3.4.min.js' %}"></script>
        <script src="{% url 'course_student_js' lesson_id=lesson.id %}"></script>
   
{% endblock %}


{% block participants_intop %}
     <span class="participants_title"> {% trans 'PARTICIPANTS' %} </span><div id="participants"> </div>
{% endblock %}

{% block js_for_innerpage %} {% endblock %}

{% block bredcrumbs %} {% endblock %}

{% block title %} Online courses {% endblock %}

{% block content %}

<div class="col-md-9" id="left_col">

    <div id="write_board" class="student_writeboard"> <h2 align="center"> {% trans 'Write board' %}  </h2></div>
    <a  href="#" class="quick_message" data-message="{% trans 'YES' %} ">{% trans 'YES' %}</a>
    <a  href="#" class="quick_message" data-message="{% trans 'NO' %}">{% trans 'NO' %}</a>
    <a  href="#" class="quick_message" data-message="{% trans 'I have got it.' %}">{% trans 'I have got it.' %}</a>
    <a  href="#" class="quick_message yellow" data-message="{% trans 'Can you be more specific please!' %}">{% trans 'Can you be more specific please!' %}</a>
    <a  href="#" class="quick_message red"  data-message="{% trans 'I dont understand!' %}">{% trans 'I dont understand!' %}</a>

    <a  href="#" class="quick_message" data-message="{% trans 'Thank you very match.' %}">{% trans 'Thank you very match.' %}</a>
    <a  href="#" class="quick_message" data-message="{% trans 'I have a question!' %}">{% trans 'I have a question!' %}</a>
</div>

<div class="col-md-3" id="right_col">

    <a href="#" id="hide_right" style="float: left;  font-size: 20px" onclick="return false;"> <span class="glyphicon glyphicon-remove-circle"> </span> </a>
    <div id="owner_cam"><h3 align="center">{% trans 'Camera is disabled' %}</h3></div>

<!--
<ul id="chat_text_messages">

</ul>
-->
<h3>{% trans 'Chat' %}</h3>

<ul id="chat_text_messages"></ul>

<form align="center">

<textarea name="text_lesson" id="chat_text_input"></textarea>
<a  href="#" class="btn btn-success" id="send_chat_text" data-replace="yes">{% trans 'Send message' %}</a>

</form>
  


</div>


 <div class="col-md-12">    

 <div id="student_cam_list"></div>
</div>




{% endblock %}

examples/co/course/templates/course_detail.html
{% extends 'base.html' %}

{% load i18n %}


{% block bredcrumbs %} {% endblock %}

{% block title %} Online courses {% endblock %}

{% block content %}

<div class="col-md-12">


<div class="well">

   <div align="center">
    <a  href="{% url 'add-me-to-course' course_id=course.id %}" class="btn theme-btn" id="registration_save">{% trans 'Subscribe' %}</a>
   </div>


 <h2>{{ course.name }}</h2>



 {{ course.requirements|safe }}

   <div align="center">
    <a  href="{% url 'add-me-to-course' course_id=course.id %}" class="btn theme-btn" id="registration_save">{% trans 'Subscribe' %}</a>
   </div>


  <h3> {% trans 'Lessons' %} </h3>

    {% for l in course.lesson_set.all %}

     <b> {{ forloop.counter }}. {{ l.name }} </b>
        <p> {{ l.desc|safe }} </p>

    {% endfor %}


</div>
   
    


{% endblock %}

examples/co/course/templates/courses_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load i18n %}
{% load thumbnail %}
{% load staticfiles %}
       
{% block js %}
    {{ block.super }}
    {{ form.media }}
        <script type="text/javascript" src="{% static 'django_ajax/js/jquery.ajax.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'django_ajax/js/jquery.ajax-plugin.min.js' %}"></script>
    <script src="{% static 'js/profile.js' %}"></script>
{% endblock %}

{% block bredcrumbs %} {% endblock %}

{% block content %}


<div class="col-md-12">



    <div class="well">
      
         
       

                <h2>{% trans 'List of your courses' %}</h2>
                
              
              <table class="table table-striped">
                <thead>
                    <tr>
                        <th>{% trans 'Image' %}</th>
                        <th>{% trans 'Name' %}</th>
                        <th>{% trans 'Is active' %}</th>
                        <th>{% trans 'Lessons' %}</th>
                        <th>{% trans 'Actions' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in courses %}
                    <tr>
                        <td>{{ c.thumb }}</td>
                        <td>{{ c.name }}</td>
                        <td>{{ c.is_active }}</td>
                        <td>

                            <table class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th>{% trans 'Image' %}</th>
                                                    <th>{% trans 'Name' %}</th>
                                                    <th>{% trans 'Is active' %}</th>
                                                    <th>{% trans 'Actions' %}</th>
                                                </tr>
                                            </thead>

                             {% for l in c.lesson_set.all %}          
                              
                                <tr>
                                 <td>{{ l.thumb }}</td>
                                 <td>{{ l.name }}</td>
                                 <td>{{ l.name }}</td>
                                 <td>
                                     <a onclick = "if (! confirm('{% trans 'Sure?' %}')) { return false; }" href="{% url 'delete-lesson' lesson_id=l.id %}">{% trans 'Delete lesson' %}</a>
                                    <a  href="{% url 'lesson-edit' id=l.id %}">{% trans 'Edit lesson' %}</a>
                                    <a href="{{l.get_absolute_url_for_owner}}">{% trans 'Start lesson' %}</a>
</td>

                                </tr>
                             {%  endfor %}           
                             </table>
                                <a  class="btn btn-success" href="{% url 'create-lesson' course_id=c.id %}">{% trans 'Create lesson' %}</a>
                  
                        </td>
                        <td> <a class="btn btn-success" href="{% url 'edit-course' course_id=c.id  %}">{% trans 'Edit course' %}</a> </td>
                       
                    </tr>
                    {% endfor %}
                </tbody>
            </table>  


       <div style="clear: both"></div>
    </div>
    

</div>

     


{% endblock %}

examples/co/course/templates/create_course.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load i18n %}
{% load thumbnail %}
{% load staticfiles %}
       
{% block js %}
    {{ block.super }}
    {{ form.media }}
        <script type="text/javascript" src="{% static 'django_ajax/js/jquery.ajax.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'django_ajax/js/jquery.ajax-plugin.min.js' %}"></script>
    <script src="{% static 'js/profile.js' %}"></script>
{% endblock %}

{% block bredcrumbs %} {% endblock %}

{% block content %}


<div class="col-md-12">



    <div class="well">
      
         
       
 <form method="post" action="" enctype="multipart/form-data">
                <h2>{% trans 'Create course' %}</h2>
                
                {% csrf_token %}
               

                <div class="form-body">
                    <div class="form-group {%if form.email.errors %}alert alert-danger{%endif%}">
                        {{ form.name.label_tag }}
                        <div class="input-group">
                            <span class="input-group-addon">
                                
                            </span>
                           {{ form.name|add_class:"form-control" }}
                        </div>
                        <span class="error-block">{{ form.name.help_text }}</span>
                        <span class="help-block">{{ form.name.errors }}</span>
                    </div>
                </div>


                <div class="form-body">
                    <div class="form-group {%if form.email.errors %}alert alert-danger{%endif%}">
                        {{ form.desc.label_tag }}
                        <div class="input-group">
                           
                           {{ form.desc|add_class:"form-control" }}
                        </div>
                        <span class="error-block">{{ form.desc.help_text }}</span>
                        <span class="help-block">{{ form.desc.errors }}</span>
                    </div>
                </div>



                <div class="form-body">
                    <div class="form-group {%if form.email.errors %}alert alert-danger{%endif%}">
                        {{ form.requirements.label_tag }}
                        <div class="input-group">
                           
                           {{ form.requirements|add_class:"form-control" }}
                        </div>
                        <span class="error-block">{{ form.requirements.help_text }}</span>
                        <span class="help-block">{{ form.requirements.errors }}</span>
                    </div>
                </div>

                <div class="form-body">
                    <div class="form-group {%if form.email.errors %}alert alert-danger{%endif%}">
                        {{ form.image.label_tag }}
                        
                            
                           {{ form.image|add_class:"form-control" }}
                           {{ form.cropping }}
                        
                        <span class="error-block">{{ form.image.help_text }}</span>
                        <span class="help-block">{{ form.image.errors }}</span>
                    </div>
                </div>
                 {{ form.owner }}

                    <div class="row">
                        <div class="col-md-12">
                            <button type="submit" class="btn theme-btn" id="registration_save">{% trans 'Save' %}</button>
                        </div>
                    </div>

            </form>

            
            


       <div style="clear: both"></div>
    </div>
    

</div>

     


{% endblock %}

examples/co/course/templates/create_lesson.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load i18n %}
{% load thumbnail %}
{% load staticfiles %}
       
{% block js %}
    {{ block.super }}
    {{ form.media }}
        <script type="text/javascript" src="{% static 'django_ajax/js/jquery.ajax.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'django_ajax/js/jquery.ajax-plugin.min.js' %}"></script>
    <script src="{% static 'js/profile.js' %}"></script>
{% endblock %}

{% block bredcrumbs %} {% endblock %}

{% block content %}


<div class="col-md-12">



    <div class="well">
      
         
       
 <form method="post" action="" enctype="multipart/form-data">
      {% csrf_token %}
      <h2>{% trans 'Create lesson' %} {% trans 'course' %} {{ course.name }}</h2>
                
      <div class="form-body">
                    <div class="form-group {%if form.email.errors %}alert alert-danger{%endif%}">
                        {{ form.name.label_tag }}
                        <div class="input-group">
                            <span class="input-group-addon">
                                
                            </span>
                           {{ form.name|add_class:"form-control" }}
                        </div>
                        <span class="error-block">{{ form.name.help_text }}</span>
                        <span class="help-block">{{ form.name.errors }}</span>
                    </div>
                </div>
                <div class="form-body">
                    <div class="form-group {%if form.email.errors %}alert alert-danger{%endif%}">
                        {{ form.desc.label_tag }}
                        <div class="input-group">
                           
                           {{ form.desc|add_class:"form-control" }}
                        </div>
                        <span class="error-block">{{ form.desc.help_text }}</span>
                        <span class="help-block">{{ form.desc.errors }}</span>
                    </div>
                </div>

   
                
                <div class="form-body">
                    <div class="form-group {%if form.email.errors %}alert alert-danger{%endif%}">
                        {{ form.image.label_tag }}
                        
                            
                           {{ form.image|add_class:"form-control" }}
                           {{ form.cropping }}
                        
                        <span class="error-block">{{ form.image.help_text }}</span>
                        <span class="help-block">{{ form.image.errors }}</span>
                    </div>
                </div>     

                 {{ form.owner }} {{ form.course }}
                    <div class="row">
                        <div class="col-md-6">
                            <button type="submit" class="btn theme-btn" id="registration_save">{% trans 'Save' %}</button>
                        </div>
                       


                    </div>
        </form>


       <div style="clear: both"></div>
    </div>
    

</div>

     


{% endblock %}

examples/co/course/templates/image_add.html
{% extends 'base.html' %}
{% load compress %}
{% load staticfiles %}





{% load i18n %}


{% block bredcrumbs %}
                    <ul class="pull-right breadcrumb">
                        <li class="active">{% trans 'Edit lesson' %}</li>

                    </ul>

{% endblock %}

{% block title %} Online courses {% endblock %}

{% block content %}

<div class="col-md-3">

<div id="owner_cam"></div>
<a href="#" id="turn_owner_cam_on"> Turn my cam on </a>


    <form action="" method="POST" enctype="multipart/form-data">
       
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save"/>
    </form>
        


</div>
<div class="col-md-9">

    <h3> Lesson # {{lessom.id}} {{lesson.name}} </h3>


</div>

     


{% endblock %}